module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier', 'prettier/react'],
  plugins: ['react', 'react-hooks', 'prettier'],
  env: {
    browser: true,
    jest: true,
  },
  globals: {
    it: true,
    expect: true,
    describe: true,
    jest: true,
    document: true,
    test: true,
    window: true,
    fetch: true,
    WebSocket: true,
    alert: true,
    screen: true,
  },
  rules: {
    semi: [2, 'always'],
    indent: 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'object-curly-spacing': ['error', 'always'],
    'jsx-a11y/media-has-caption': 0,
    'jsx-a11y/click-events-have-key-events': 0,
    'no-console': 0,
    'no-useless-concat': 0,
    'no-param-reassign': 0,
    'react/state-in-constructor': 0,
    'max-len': [2, { ignoreUrls: true, ignoreRegExpLiterals: true }],
    'react/jsx-indent': 0,
    'react/jsx-wrap-multilines': 0,
    'react/jsx-filename-extension': 0,
    'implicit-arrow-linebreak': 0,
    'import/no-named-as-default': 0,
    'import/newline-after-import': 1,
    'react/no-unescaped-entities': 0,
    'react/jsx-first-prop-new-line': [1, 'multiline'],
    'import/prefer-default-export': 0,
    'class-methods-use-this': 0,
    'operator-linebreak': 0,
    'react/require-default-props': 0,
    'react/react-in-jsx-scope': 0,
    'react/no-danger': 0,
    'react/prefer-stateless-function': 0,
    'react/no-array-index-key': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'no-return-assign': 0,
    'react/destructuring-assignment': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-one-expression-per-line': 0,
    'react/static-property-placement': 0,
    'react/jsx-props-no-spreading': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-cycle': 0,
    'global-require': 0,
    'no-restricted-globals': 0,
    'import/no-dynamic-require': 0,
    quotes: [2, 'single', { avoidEscape: true }],
  },
  overrides: [
    {
      files: '*.mdx',
      parser: 'eslint-mdx',
    },
  ],
};
